### PR TITLE
b!maps

### PR DESCRIPTION
**Pull request by lionants02**
## Important. I haven't tested it because I can't do Discord bot.
I have an idea.

Step 1: I copied the contents of the song.js file.
Step 2: I edited the content of lines 16 and 44.

api doc
https://docs.beatsaver.com/endpoints/maps.html#maps-detail-key

Please check
Thank you

### CODE REVIEW

**Comment by SpectrixDev** [comment]
I'm a little confused on what this adds. Could you explain before we test if it works?

**Comment by SamHep0803** [comment]
Yeah, we would like just a bit info on this as right now, I can't see any difference in using the /maps endpoint vs the /search endpoint

**Comment by SamHep0803** [comment]
Ah I think I figured out what you are trying to get at here. 

*for future reference it's for getting a map by its ID*

Sorry but me and Spectrix have discussed before privately that getting a map by its ID is sort of useless due to you needing to go to the BeatSaver website to get the ID anyways. 

If you make any more pull requests, do you mind giving a little more detail just so that we don't have to go digging trying to figure out the added feature. :)

**Comment by lionants02** [comment]
I have a problem with duplicate hit songs. What should I do?
I really like the detailed display of the bot.

Thank you

**Comment by SamHep0803** [comment]
Hi,

Thanks for the positive feedback!

Would you mind creating a new issue for the problem you are having right now as this isn't really the place to do it. (and please make sure you give us lots of details so we can fix the issue)

**Comment by SpectrixDev** [comment]
I think we initially misunderstood you. I think I get what you mean now though. And after private discussion, we've decided that we'll add a map by ID argument to the bot (if this is what you meant)

For example, `b!map id da60` and `b!map name Midnight Lady`

Is that what you were requesting?

**Comment by SamHep0803** [comment]
Aaaaand he created an issue lol (#3)

**Pull request closed without merging**
